apiVersion: v1
kind: Service
metadata:
  name: idm-api
  labels:
    app.kubernetes.io/name: idm
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: idm
    app.kubernetes.io/component: api
