apiVersion: v1
kind: ServiceAccount
metadata:
  name: idm-api
  namespace: idm
  annotations:
    # 阿里云 ACS RRSA (RAM Role for Service Accounts)
    # 配置 Workload Identity 后, Pod 可拿到此 SA 对应的 RAM 角色临时凭证
    alibabacloud.com/rrsa: "true"
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: idm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: idm-web
  namespace: idm
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: idm
