apiVersion: apps/v1
kind: Deployment
metadata:
  name: idm-web
  labels:
    app.kubernetes.io/name: idm
    app.kubernetes.io/component: web
    app.kubernetes.io/version: "0.1.0"
spec:
  # ACS: 1 副本即可 (静态 SPA)
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: idm
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: idm
        app.kubernetes.io/component: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      serviceAccountName: idm-web
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: idm-web:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # API base URL 通过环境变量注入到 nginx.conf (kustomize 用 ConfigMap 替换)
          env:
            - name: API_BASE_URL
              value: "/api"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
