apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idm-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: idm-api
spec:
  project: idm
  source:
    repoURL: git@github.com:company/idm.git
    targetRevision: HEAD
    path: deploy/helm/idm-api
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: idm-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
